language: php
php:
  - '5.6'
services:
  - docker
env:
 before_install:

  # Install kalabox
  - sudo apt-get -y update
  - sudo apt-get -y install iptables cgroup-bin bridge-utils curl

install:

  # Install composer deps
  - composer install
  - phing -debug
